insert into author (id, name, birth_date, particularity) values (1, 'ggrimmert0', 'Crimson', null);
insert into author (id, name, birth_date, particularity) values (2, 'jnorthbridge1', 'Mauv', null);
insert into author (id, name, birth_date, particularity) values (3, 'sshipsey2', 'Aquamarine', 'In blandit ultrices enim.');
insert into author (id, name, birth_date, particularity) values (4, 'jcote3', 'Indigo', 'Phasellus in felis. Donec semper sapien a libero.');
insert into author (id, name, birth_date, particularity) values (5, 'acoultous4', 'Yellow', null);
insert into author (id, name, birth_date, particularity) values (6, 'rdreinan5', 'Green', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into author (id, name, birth_date, particularity) values (7, 'pbwye6', 'Mauv', null);
insert into author (id, name, birth_date, particularity) values (8, 'scurragh7', 'Maroon', null);
insert into author (id, name, birth_date, particularity) values (9, 'moscully8', 'Turquoise', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into author (id, name, birth_date, particularity) values (10, 'zskelington9', 'Blue', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into author (id, name, birth_date, particularity) values (11, 'jlampena', 'Purple', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into author (id, name, birth_date, particularity) values (12, 'spestrickeb', 'Yellow', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into author (id, name, birth_date, particularity) values (13, 'mmenichic', 'Orange', 'Etiam faucibus cursus urna.');
insert into author (id, name, birth_date, particularity) values (14, 'biglesiad', 'Purple', 'Praesent id massa id nisl venenatis lacinia.');
insert into author (id, name, birth_date, particularity) values (15, 'nlambdene', 'Red', null);
insert into author (id, name, birth_date, particularity) values (16, 'jgiveenf', 'Blue', 'Donec semper sapien a libero.');
insert into author (id, name, birth_date, particularity) values (17, 'rscarling', 'Aquamarine', null);
insert into author (id, name, birth_date, particularity) values (18, 'vnowakowskih', 'Aquamarine', null);
insert into author (id, name, birth_date, particularity) values (19, 'oapperleyi', 'Crimson', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into author (id, name, birth_date, particularity) values (20, 'gtannerj', 'Teal', null);
insert into author (id, name, birth_date, particularity) values (21, 'mriordank', 'Blue', null);
insert into author (id, name, birth_date, particularity) values (22, 'vmccarrelll', 'Yellow', null);
insert into author (id, name, birth_date, particularity) values (23, 'dwildgoosem', 'Teal', 'Morbi a ipsum. Integer a nibh.');
insert into author (id, name, birth_date, particularity) values (24, 'ejaggersn', 'Blue', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into author (id, name, birth_date, particularity) values (25, 'jlacazeo', 'Purple', null);
insert into author (id, name, birth_date, particularity) values (26, 'tbysouthp', 'Mauv', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into author (id, name, birth_date, particularity) values (27, 'clauritzenq', 'Pink', 'Nunc purus.');
insert into author (id, name, birth_date, particularity) values (28, 'nchicchettor', 'Crimson', null);
insert into author (id, name, birth_date, particularity) values (29, 'fwardlows', 'Indigo', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into author (id, name, birth_date, particularity) values (30, 'sbonwickt', 'Red', 'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into author (id, name, birth_date, particularity) values (31, 'cshimonyu', 'Red', 'Quisque ut erat.');
insert into author (id, name, birth_date, particularity) values (32, 'vjobbinsv', 'Purple', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into author (id, name, birth_date, particularity) values (33, 'dickoviczw', 'Fuscia', 'Quisque ut erat.');
insert into author (id, name, birth_date, particularity) values (34, 'klievesleyx', 'Green', 'Duis mattis egestas metus.');
insert into author (id, name, birth_date, particularity) values (35, 'dvinteny', 'Violet', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into author (id, name, birth_date, particularity) values (36, 'pandreuttiz', 'Red', null);
insert into author (id, name, birth_date, particularity) values (37, 'sskupinski10', 'Yellow', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into author (id, name, birth_date, particularity) values (38, 'epetto11', 'Teal', null);
insert into author (id, name, birth_date, particularity) values (39, 'schaman12', 'Crimson', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into author (id, name, birth_date, particularity) values (40, 'wfilipponi13', 'Violet', 'Nulla ac enim.');
insert into author (id, name, birth_date, particularity) values (41, 'skondrat14', 'Indigo', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into author (id, name, birth_date, particularity) values (42, 'acassel15', 'Indigo', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into author (id, name, birth_date, particularity) values (43, 'mverna16', 'Green', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into author (id, name, birth_date, particularity) values (44, 'tduncklee17', 'Orange', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into author (id, name, birth_date, particularity) values (45, 'rpobjoy18', 'Maroon', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into author (id, name, birth_date, particularity) values (46, 'cboick19', 'Goldenrod', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into author (id, name, birth_date, particularity) values (47, 'ntenman1a', 'Maroon', 'Donec vitae nisi.');
insert into author (id, name, birth_date, particularity) values (48, 'dginley1b', 'Blue', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into author (id, name, birth_date, particularity) values (49, 'gsteabler1c', 'Violet', null);
insert into author (id, name, birth_date, particularity) values (50, 'kclaris1d', 'Maroon', 'Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');